<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfcBase\Module'                                    => __DIR__ . '/Module.php',
    'ZfcBase\Form\ProvidesEventsForm'                   => __DIR__ . '/src/ZfcBase/Form/ProvidesEventsForm.php',
    'ZfcBase\Mapper\Exception\ExceptionInterface'       => __DIR__ . '/src/ZfcBase/Mapper/Exception/ExceptionInterface.php',
    'ZfcBase\Mapper\Exception\InvalidArgumentException' => __DIR__ . '/src/ZfcBase/Mapper/Exception/InvalidArgumentException.php',
    'ZfcBase\Mapper\AbstractDbMapper'                   => __DIR__ . '/src/ZfcBase/Mapper/AbstractDbMapper.php',
    'ZfcBase\EventManager\EventProvider'                => __DIR__ . '/src/ZfcBase/EventManager/EventProvider.php',
    'ZfcBase\Module\AbstractModule'                     => __DIR__ . '/src/ZfcBase/Module/AbstractModule.php',
);